GET http://localhost:5000/barang

###
GET http://localhost:5000/barang/2

###
POST http://localhost:5000/barang
Content-Type: application/json 

{
    "nm_barang": "Pulpen",
    "kategori": "ATK",
    "deskripsi": "Ini pulpen buat nulis",
    "harga": 3000,
    "stok": 10
}

###
PATCH  http://localhost:5000/barang/1
Content-Type: application/json

{
    "nm_barang": "Pensil HB",
    "kategori": "ATK",
    "deskripsi": "Ini pensil buat nulis",
    "harga": 3000,
    "stok": 10
}

###
DELETE http://localhost:5000/barang/2
